collections:
- posts
- projects

paginate: 5
paginate_path: "/blog/page:num"

blog_name: "Swift Connection"
blog_subheader: "A Swift Blog brought to you by TechRapport.com"

copyright: "Tech Rapport"


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: techrapportcom

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-68833574-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://techrapport.com