collections:
- posts
- projects

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      path: ""
      layout: "post"
      author: "Tech Rapport"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Tech Rapport"

author: "Tech Rapport"

paginate: 4
paginate_path: "/blog/page:num/"

blog_name: "Swift Connection"
blog_subheader: "A Swift Blog brought to you by TechRapport.com"
blog_image_path: "/assets/images/blog/"

copyright: "Tech Rapport"


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: techrapportcom

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-68833574-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://techrapport.com