#Site variables
author: "Tech Rapport"
name: "Tech Rapport"
header: "Creative Software"
tagline: "Fostering relationships between business and technology is what we do best"
tagline_old: "Where Technology and Business Meet"
copyright: "Tech Rapport"
url: "http://techrapport.com"

google_analytics: UA-68833574-1
paginate: 4
paginate_path: "/blog/page:num/"
disqus: techrapportcom

#Blog variables
blog_image_path: /assets/images/blog/
blog_name: "Swift Connection"
blog_subheader: "A Swift Blog brought to you by TechRapport.com"

#Collections:
collections: 
  - posts
  - projects

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji
  - jekyll-redirect-from
  #- jekyll-mentions#--Doesn;t work, investigate html-pipeline error.

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

#Defaults
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      author: "Tech Rapport"
      layout: post
      path: ""
  - 
    scope: 
      path: ""
      type: pages
    values: 
      author: "Tech Rapport"
      layout: page
markdown: redcarpet
highlighter: pygments

#Social icons:
footerlinks: 
  - 
    iclass: "fa fa-send-o"
    title: Email
    url: "mailto:"
    username: info@techrapport.com
  - 
    iclass: "fa fa-github"
    title: GitHub
    url: "https://github.com/"
    username: techrapport
  - 
    iclass: "fa fa-linkedin"
    title: linkedin
    url: "https://www.linkedin.com/in/"
    username: techrapport
  - 
    iclass: "fa fa-stack-overflow"
    title: linkedin
    url: "https://www.stackoverflow.com/"
    username: techrapport
  - 
    iclass: "fa fa-twitter"
    title: Twitter
    url: "https://www.twitter.com/"
    username: tech_rapport
  - 
    iclass: "fa fa-google-plus"
    title: techrapport
    url: "https://plus.google.com/"
    username: "101168809038593931433/"# anything in your profile username that comes after plus.google.com/
  - 
    iclass: "fa fa-youtube"
    title: techrapport 
    url: "https://youtube.com/"
    username: "channel/UC2iYWXVQlPa76aQlADYocow/"
  -
    iclass: "fa fa-rss"
    title: feed.xml
    url: 
    username: "feed.xml"
