#Site variables

title: Tech Rapport
name: Tech Rapport
header: "Creative Software"
tagline: "Fostering relationships between business and technology is what we do best"
description: "Tech Rapport, creative software, web design, marketing, SEO, and data architecture. At TechRapport, we believe that technology and business go hand-in-hand.  Work with us to create a better future for your business and generate rapport with your technology now."
copyright: Tech Rapport #move to author?
url: "http://techrapport.com"
image_path: /assets/images/

author: 
  name: Ryan Collins
  email: info@techrapport.com
  company: "Tech Rapport"
  #Make sure to reconfigure footer-links:
  avatar:
  bio:
  twitter:
  facebook:
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +yourid

#webmaster stuff
google_analytics: UA-68833574-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

#Jekyll & Markdown vars:
paginate: 4
paginate_path: "/blog/page:num/"
disqus: techrapportcom
markdown: kramdown
highlighter: pygments
future: true
timezone: America/New_York

#Blog variables
blog_image_path: /assets/images/blog/
blog_name: "Swift Connection"
blog_subheader: "A Swift Blog brought to you by TechRapport.com"

#Collections:
collections: 
  - posts
  - projects

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji
  - jekyll-redirect-from
  #- jekyll-mentions#--Doesn;t work, investigate html-pipeline error.

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

#Defaults
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      author: "Tech Rapport"
      layout: post
      path: ""
      permalink: /blog/:categories/:year/:month/:day/:title/
  - 
    scope: 
      path: ""
      type: pages
    values: 
      author: "Tech Rapport"
      layout: page
  -
    scope:
      path: ""
      type: projects
    values:
      author: "Tech Rapport"
      layout: default

#Site Map Vars:
sitemap:
  lastmod: 2015-01-23
  priority: 0.7
  changefreq: monthly
  exclude: yes

#Social icons:
footerlinks: 
  - 
    iclass: "fa fa-send-o"
    title: Email
    url: "mailto:"
    username: info@techrapport.com
  - 
    iclass: "fa fa-github"
    title: GitHub
    url: "https://github.com/"
    username: techrapport
  - 
    iclass: "fa fa-linkedin"
    title: linkedin
    url: "https://www.linkedin.com/in/"
    username: techrapport
  - 
    iclass: "fa fa-stack-overflow"
    title: linkedin
    url: "https://www.stackoverflow.com/"
    username: techrapport
  - 
    iclass: "fa fa-twitter"
    title: Twitter
    url: "https://www.twitter.com/"
    username: tech_rapport
  - 
    iclass: "fa fa-google-plus"
    title: techrapport
    url: "https://plus.google.com/"
    username: "101168809038593931433/"# anything in your profile username that comes after plus.google.com/
  - 
    iclass: "fa fa-youtube"
    title: techrapport 
    url: "https://youtube.com/"
    username: "channel/UC2iYWXVQlPa76aQlADYocow/"
  -
    iclass: "fa fa-rss"
    title: feed.xml
    url: 
    username: "feed.xml"
