author: "Tech Rapport"
blog_image_path: /assets/images/blog/
blog_name: "Swift Connection"
blog_subheader: "A Swift Blog brought to you by TechRapport.com"
collections: 
  - posts
  - projects
copyright: "Tech Rapport"
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      author: "Tech Rapport"
      layout: post
      path: ""
  - 
    scope: 
      path: ""
      type: pages
    values: 
      author: "Tech Rapport"
      layout: page
disqus: techrapportcom

footerlinks: 
  - 
    iclass: "fa fa-send-o"
    title: Email
    url: "mailto:"
    username: info@techrapport.com
  - 
    iclass: "fa fa-github"
    title: GitHub
    url: "https://github.com/"
    username: techrapport
  - 
    iclass: "fa fa-linkedin"
    title: linkedin
    url: "https://www.linkedin.com/in/"
    username: techrapport
  - 
    iclass: "fa fa-stack-overflow"
    title: linkedin
    url: "https://www.stackoverflow.com/"
    username: techrapport
  - 
    iclass: "fa fa-twitter"
    title: Twitter
    url: "https://www.twitter.com/"
    username: techrapport
  - 
    iclass: "fa fa-google-plus"
    title: techrapport
    url: "https://plus.google.com/"
    username: "101168809038593931433/"# anything in your profile username that comes after plus.google.com/
  - 
    iclass: "fa fa-youtube"
    title: techrapport 
    url: "https://youtube.com/"
    username: "channel/UC2iYWXVQlPa76aQlADYocow/"
  -
    iclass: "fa fa-rss"
    title: feed.xml
    url: "{{ site.baseurl }}"
    username: "feed.xml"

google_analytics: UA-68833574-1
paginate: 4
paginate_path: "/blog/page:num/"
url: "http://techrapport.com"
