#Site variables
title: Tech Rapport
header:
  descriptors: 
    - Creative,
    - Powerful,
    - Advanced,
    - Stunning,
    - Innovative
  text: Software

description: "Tech Rapport, creative software, web design, marketing, SEO, and data architecture. At TechRapport, we believe that technology and business go hand-in-hand.  Work with us to create a better future for your business and generate rapport with your technology now."
tagline: "Fostering relationships between business and technology is what we do best"
copyright: Tech Rapport
url: http://techrapport.com
image_path: /assets/images/
icon_path: /assets/images/icons/
reading_time: true
words_per_minute: 200
logo: /logo.png
baseurl: ''
excerpt-seperator: '<!-- more -->'

#Delete author once all updated to owner:

owner:
  name: Ryan
  author: 'Ryan C.'
  address: 
  phone: 617-299-9722
  email: info@techrapport.com
  company: Tech Rapport
  site:           http://techrapport.com
  avatar:         me-avatar150x150.jpeg
  bio:            "I am a passionate and creative software developer.  I love the work that I do and I love sharing it with the world.  Please get in touch with me if you want to work together to create something."
  email:          info@techrapport.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: tech_rapport
  facebook: 
  github: techrapport
  stackexchange: techrapport
  linkedin: techrapport
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+'
  google_plus: +101168809038593931433

# Analytics and webmaster tools stuff goes here
google_analytics: UA-68833574-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

paginate: 5
paginate_path: "/blog/page:num/"
disqus_shortname: techrapportcom

#Blog variables
blog_image_path: /assets/images/blog/
blog_name: "Swift Connection"
blog_subheader: "A Swift Blog brought to you by TechRapport.com"
#Markdown vars
markdown: redcarpet
highlighter: pygments


redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "underline", "highlight", "quote", "footnote_ref"]

#Collections:
collections: 
  posts:
  projects:
    output: true
    render: true

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji
  - jekyll-redirect-from
  # - jekyll-mentions

sass:
  sass_dir: _sass
  style: compressed

# Exclude these files from your production _site
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md, CNAME, node_modules]

#Defaults
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      author: "Tech Rapport"
      layout: post
      path: "/blog/"
      permalink:
  - 
    scope: 
      path: ""
      type: pages
    values: 
      author: "Tech Rapport"
      layout: page
  -
    scope:
      path: ""
      type: projects
    values:
      author: "Tech Rapport"
      layout: project
      permalink: /:collection/:path/index.html
      render: true
      output: true

#Site Map Vars:
sitemap:
  lastmod: 2015-01-23
  priority: 0.7
  changefreq: monthly
  exclude: yes

#Social icons:
footerlinks: 
  - 
    iclass: "fa fa-send-o"
    title: Email
    url: "mailto:"
    username: info@techrapport.com
  - 
    iclass: "fa fa-github"
    title: GitHub
    url: "https://github.com/"
    username: techrapport
  - 
    iclass: "fa fa-linkedin"
    title: linkedin
    url: "https://www.linkedin.com/in/"
    username: techrapport
  - 
    iclass: "fa fa-stack-overflow"
    title: stackoverflow
    url: "https://www.stackoverflow.com/"
    username: techrapport
  - 
    iclass: "fa fa-twitter"
    title: Twitter
    url: "https://www.twitter.com/"
    username: tech_rapport
  - 
    iclass: "fa fa-google-plus"
    title: techrapport
    url: "https://plus.google.com/"
    username: "101168809038593931433/"# anything in your profile username that comes after plus.google.com/
  - 
    iclass: "fa fa-youtube"
    title: techrapport 
    url: "https://youtube.com/"
    username: "channel/UC2iYWXVQlPa76aQlADYocow/"
  -
    iclass: "fa fa-rss"
    title: rssfeed.xml
    url: '{{site.url}}'
    username: "rssfeed.xml"
