header: Services
subheader: What can we do for you?

services:
  - title: "Progressive Web"
    key: 0
    icon: "icon-Wifi"
    description: "I have years of experience and expertise building progressive web software built for the Internet of Things.  I have built software in use in appliances and smart products across the world and can help you to build out your product using the lateset and greatest web technologies available today."
  - title: "Agile Project Management"
    key: 5
    icon: "icon-Calendar-4"
    description: "Agile software development helps you to get software into the hands of your client faster.  Utilizing Scrum and other Agile methodologies, I can help you to keep your project moving on schedule."
  - title: "Mobile Software"
    key: 1
    icon: "icon-Smartphone-4"
    description: "My passion is for building web and mobile software.  I have experience creating iOS applications with Swift, and cross-platform mobile applications with React Native and Ionic.  I focus on creating web software with a mobile-first approach using responsive web technologies and progressive JavaScript frameworks."
  - title: "Data Architecture"
    key: 3
    icon: "icon-Big-Data"
    description: "You don't need to be Google to employ an intelligent cloud computing system.  With nearly 8 years experience architecting scalable data systems, I can help you to implement the latest and greatest real-time distributed server technologies, including Docker, Jenkins, NodeJS and others."
  - title: "SEO and Social Media"
    key: 2
    icon: "icon-Cloud-Email"
    description: "Harness the power of big data and use it to understand your consumers and directly market to your target audience.  With extensive experience in data and research analysis, I can help to give your business the edge it needs to thrive."
  - title: "Pro Bono Consulting"
    key: 4
    icon: "icon-Consulting"
    description: "Through the <a href=\"http://hacksmiths.io/\">Hacksmiths.io</a> platform, I offer Pro Bono software development and consulting services to charitable and philanthrophic organizations.  Please contact me if your charitable organization can the help of a talented group of professional software developers!"
