header: Services
subheader: What can we do for you?

services:
  - title: "Web Design"
    key: 0
    icon: "icon-Wifi"
    description: "Create beautiful websites to showcase your talent and expand your web presence.  We can help you create websites and web applications that users will love to visit and use.  Get help planning your website from the ground up or redesign it with the most innovative technologies."
  - title: "Machine Learning"
    key: 5
    icon: "fa-graduation-cap"
    description: "Use highly intelligent prediction and machine learning software to help drive your business decisions.  We can help you implement intelligent data systems and software that will work with you and your business."
  - title: "Mobile Software"
    key: 1
    icon: "icon-Smartphone-4"
    description: "Our passion is mobile development and we believe in creating mobile first software and web applications.  With professional certification in iOS development and extensive experience in mobile web development, we can help you to reach your customers on their mobile devices."
  - title: "Data Architecture"
    key: 3
    icon: "icon-Big-Data"
    description: "Let us help your business harness the power of big data.  We can help you design and implement scalable NoSQL or SQL data systems, utilize the world's most powerful APIs and help you use your data to its full potential with custom data systems and reporting software."
  - title: "SEO and Social Media"
    key: 2
    icon: "icon-Cloud-Email"
    description: "Harness the power of big data and use it to understand your consumers and directly market to your target audience.  With extensive training in Google SEO and Analytics, we can give your business the edge it needs to thrive."
  - title: "Consulting"
    key: 4
    icon: "icon-Consulting"
    description: "We offer a wide range of IT consulting services.  Contact us now to talk about what we can do to help your business excel."
